# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because no comments have been made in a month.  Unless comments are made in the next week (or the 'pinned' label is applied), this issue will be closed automatically in a week.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed automatically, because no comments have been made in the week since it was marked as stale.

